### PR TITLE
fixed assistant dashboard

### PR DESCRIPTION
**Pull request by Clish254**
# Description

Please include a summary of the change and which issue is fixed. Add a refrence to the issue that was fixed! 
The assistant dashboard is supposed to return exactly the same data as /assistant/:assistantId, i updated it to do that. We also had errors in the assistant dashboard logic. Which i have resolved.
## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by chinazaaa** [comment]
Is login assistant working?

**Comment by Clish254** [comment]
I used the login/assistant endpoint to log in in curl. I think @script is working on the logic to make assistants log in from the same endpoint.

**Comment by chinazaaa** [comment]
Okay

**Comment by Clish254** [comment]
I've fixed assistant login as well, you can check and merge

**Pull request merged**
