### PR TITLE
fix  assistant/update/:assistant_id

### PR DESCRIPTION
**Pull request by olawalejuwonm**
# Description

Please include a summary of the change and which issue is fixed. Add a refrence to the issue that was fixed! 
#233 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

Please check this screenshot accordingly
This is the initial state of the endpoint
Screenshot (17)

This is after updating the endpoint - take note of the endpoint and the request body
Screenshot (19)

This is the final work done - updated proof of the endpoint
Screenshot (20)

### CODE REVIEW

**Comment by ajdelgados** [comment]
You aren't update the assistant, you are update store admin

**Comment by olawalejuwonm** [comment]
I just spoke with @Megxos  am updating it now

**Comment by olawalejuwonm** [comment]
Screenshot (23)
I just corrected that now please check @ajdelgados

**Comment by chinazaaa** [comment]
update your PR

Its behind

**Comment by olawalejuwonm** [comment]
@Megxos  please review
Screenshot (26)
Screenshot (25)

**Comment by olawalejuwonm** [comment]
@Megxos please kindly update the docs

**Pull request merged**
