### PR TITLE
Transaction fix 1

### PR DESCRIPTION
**Pull request by kenny-67**
# Description

A user can now create transaction

details to provide when testing {

"amount"
    "interest"
    "total_amount"
    "description"
    "phone_number": A valid customer phone number
    "store_name": A valid store name
    "transaction_role"
    "transaction_name"

## Type of change
- [* ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:
- [* ] My code follows the style guidelines of this project
- [* ] I have performed a self-review of my own code
- [* ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [*] My changes generate no new warnings

transaction-fix

### CODE REVIEW

**Comment by chinazaaa** [comment]
what package did you add and why?

**Comment by kenny-67** [comment]
None

**Comment by kenny-67** [comment]
No package was needed

**Comment by buka4rill** [comment]
Resolve your conflict

**Pull request closed without merging**
