### PR TITLE
Fixed issue #76: API no longer return html page

### PR DESCRIPTION
**Pull request by Hack-Light**
# Description

Deleted the error-page.js because it generates error. The error handler can only work if placed in the app.js file

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

github

Here is the picture of the docs page.
I had another app using port 3000 so I changed the port to port 5000 on my machine

github2

### CODE REVIEW

**Comment by buka4rill** [comment]
Also show me a screenshot of a page that is not supposed to return an error. Like the localhost:3000 route

**Comment by Megxos** [comment]
Let's give him

**Comment by buka4rill** [comment]
I need to make sure other routes are not broken

**Comment by Megxos** [comment]
You code has an error, please fix it
Screenshot from 2020-06-27 18-32-11

**Comment by Megxos** [comment]
Thank you

**Pull request merged**
