### PR TITLE
Completed debt_reminders @BlackBeard

### PR DESCRIPTION
**Pull request by Wenykeny**
# Description
- Completed debt_reminders.
- Added an update and delete features to the debt_reminders.
- No fix was done on it

Please include a summary of the change and which issue is fixed. Add a reference to the issue that was fixed! 

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by naijauser** [comment]
Do this -> Please include a summary of the change and which issue is fixed. Add a reference to the issue that was fixed!

**Comment by Wenykeny** [comment]
# I just added new feature to the debt_reminder @naijauser .
To update the messages and delete them.
- New feature (non-breaking change which adds functionality)

**Comment by chinazaaa** [comment]
Resolve  conflicts

**Comment by Megxos** [comment]
These eddpoints don't work
Screenshot from 2020-06-27 20-06-51

**Pull request closed without merging**
