### PR TITLE
Debt fix

### PR DESCRIPTION
**Pull request by judgegodwins**
# Description

Fix broken create debt route at `/debt/new`
Fixed issue #149 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

Screenshot from 2020-06-27 22-27-32
Screenshot from 2020-06-27 20-59-01

### CODE REVIEW

**Comment by chinazaaa** [comment]
Resolve conflicts

**Comment by judgegodwins** [comment]
@chinazaaa I've resolved the conflicts

**Comment by buka4rill** [comment]
Why are you sending token in the request body na? If you had a UI form, would you add token there as a parameter?

**Comment by judgegodwins** [comment]
@buka4rill Token can be sent from anywhere you can check the auth middleware, I didn't write it.
It can be sent from the header or body, it'll still work

**Comment by judgegodwins** [comment]
Screenshot from 2020-06-28 07-03-38

**Comment by chinazaaa** [comment]
Seen

**Pull request merged**
