### PR TITLE
Transaction fix

### PR DESCRIPTION
**Pull request by judgegodwins**
# Description
Fix Create-Transaction Route
Fixes issue #115 
## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by chinazaaa** [comment]
awaiting screenshot

**Comment by kenny-67** [comment]
@chinazaaa i have a fix for this just in case this is not accepted

**Comment by judgegodwins** [comment]
@chinazaaa here's a screenshot, sorry I didn't use postman
Screenshot from 2020-06-27 17-12-47

**Comment by buka4rill** [comment]
Please test with Postman. This is supposed to be a post request. (yes/no?)

**Comment by judgegodwins** [comment]
@buka4rill  it is a post request. You'll see the data there

**Pull request closed without merging**
